<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "golb"
 * Auto generated by Extension Builder 2015-02-10
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Golb',
    'description' => 'Golb - Blog The Page Way',
    'category' => 'plugin',
    'author' => 'Marcel Wieser, Philipp Thiele',
    'author_email' => 'typo3dev@marcel-wieser.de, philipp.thiele@phth.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);